scrape_configs:
  - job_name: 'jmx'
    scrape_interval: 10s
    static_configs:
      - targets:
        - '172.17.0.1:4318'
        - 'datahub-gms:4318'
        - 'datahub-mae-consumer:4318'
        - 'datahub-mce-consumer:4318'
        - 'datahub-frontend-react:4318'
