source:
  type: s3
  config:
    path_specs:
      - include: "s3://production.data-lake.eu-west-1/*.*"
    aws_config:
      aws_access_key_id: "${AWS_ACCESS_KEY_ID}"
      aws_secret_access_key: '${AWS_SECRET_KEY}'
      aws_region: eu-west-1
    env: "PROD"
    profiling:
      enabled: false

sink:
  type: "datahub-rest"
  config:
    server: "http://datahub-gms:8080"
