name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: datahub-runner
    
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v4

      - name: Deploy DataHub to EC2
        run: |
          echo "🚀 Deploying DataHub to EC2..."
          cd /home/ubuntu/datahub

          echo "📦 Pulling latest code..."
          git pull origin main

          echo "🧾 Making deploy script executable..."
          chmod +x deploy/ec2-deploy.sh

          echo "🏃 Running deployment script..."
          bash -eux deploy/ec2-deploy.sh
