name: Deploy DataHub

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Permissions for OIDC
permissions:
  id-token: write
  contents: read

# AWS region
env:
  AWS_REGION: eu-west-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::179143349265:role/datahub-oidc-github-actions
          aws-region: eu-west-1

      - name: Execute commands via SSM
        id: execute_command
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --document-name AWS-RunShellScript \
            --targets "Key=tag:Name,Values=production-datahub-server" \
            --parameters '{
              "commands":[
                "cd datahub",
                "git pull origin main",
                "cd docker",
                "docker-compose -p datahub pull",
                "docker-compose -p datahub up -d"
              ]
            }' \
            --comment "Deploying DataHub" \
            --query "Command.CommandId" \
            --output text)
          echo "command_id=$COMMAND_ID" >> $GITHUB_OUTPUT

      - name: Wait for SSM command to finish
        run: sleep 15

      - name: Fetch SSM command output
        run: |
          aws ssm list-command-invocations \
            --command-id "${{ steps.execute_command.outputs.command_id }}" \
            --details \
            --query "CommandInvocations[].CommandPlugins[].{Status:Status,Stdout:Output,Stderr:ErrorOutput}" \
            --output table
