name: Deploy DataHub

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Permissions for OIDC
permissions:
  id-token: write
  contents: read

# AWS region
env:
  AWS_REGION: eu-west-1

jobs:
  deploy:
    name: Deploy DataHub via OIDC + SSM
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository (for logs/reference)
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::179143349265:role/datahub-oidc-github-actions
          role-session-name: "datahub-oidc-github-actions-${{ github.run_id }}"
          aws-region: ${{ env.AWS_REGION }}

      - name: Execute commands via SSM
        id: execute_command
        run: |
          INSTANCE_ID="${{ secrets.AWS_INSTANCE_ID }}"
          
          COMMAND_ID=$(aws ssm send-command \
          --instance-ids "$INSTANCE_ID" \
          --document-name "AWS-RunShellScript" \
          --parameters 'commands=[
           "cd datahub",
           "git pull origin main",
           "cd docker",
           "docker-compose -p datahub pull",
           "docker-compose -p datahub up -d"
          ]' \
          --comment "Deploying DataHub" \
          --query "Command.CommandId" \
          --output text)
          
          echo "command_id=$COMMAND_ID" >> $GITHUB_OUTPUT

      - name: Wait for SSM command to finish
        run: sleep 15

      - name: Output execution via SSM
        run: |
          INSTANCE_ID="${{ secrets.AWS_INSTANCE_ID }}"
          COMMAND_ID="${{ steps.execute_command.outputs.command_id }}"
          
          aws ssm list-command-invocations \
            --command-id "$COMMAND_ID" \
            --details \
            --instance-id "$INSTANCE_ID" \
            --query "CommandInvocations[].CommandPlugins[].{Status:Status,Stdout:Output,Stderr:ErrorOutput}" \
            --output table